CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference VARCHAR(255) NOT NULL,
    customer_id VARCHAR(255) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_payment_reference UNIQUE (reference)
);
